# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yardstick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=56)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
